### ISSUE TITLE
Feature Request: Add multiple decks

### ISSUE THREAD

**Issue by i2y4n** [deck-of-cards/deck-of-cards#61]
I'd like to be able to add multiple decks along with jokers

**Comment by pakastin** [comment]
Coming soon in the new version!

**Comment by i2y4n** [comment]
Sweet, that and a few tweaks to make using the game easier and quicker and this will be used all the time with my friends and I. Especially right now with the quarantine orders.

**Comment by pakastin** [comment]
Yeah, this repo will be updated as the new library (https://github.com/deck-of-cards/deck-of-cards/tree/next). [deck.of.cards](https://deck.of.cards) will be published as separate repo which uses the same library. There will also be open source game library, so that anyone can create games there. I've also planned game designer, so that anyone can create custom single/multiplayer games easily.

Even card graphics will be easily designable:
https://github.com/deck-of-cards/generate-cards
